name: Run Tests with Chrome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libgconf-2-4 libxi6 libxrandr2 libatk1.0-0 libxcursor1 libxdamage1 libxcomposite1 libasound2 libpangocairo-1.0-0 libxss1 libxext6

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\.0' | head -1)
          wget https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run tests
        run: |
          # Execute seus testes aqui que utilizam o Chrome
          # Por exemplo, se você estiver usando Maven:
          mvn test
